import type { Metadata } from "next";
import { SpeedInsights } from "@vercel/speed-insights/next";
import "../@styles/globals.css";
import { pretendard } from "./fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={`${pretendard.className} antialiased`}>
        {children}
        <SpeedInsights />
      </body>
    </html>
  );
}
